### ISSUE TITLE
No unicode restrictions for new items

### ISSUE THREAD

**Issue by shonviv** [Abdi-F/EECS3311-Group-13#2]
It's possible to use any unicode characters on the name of an item, including Right to Left characters that can result in the following:
![image](https://user-images.githubusercontent.com/20226454/225698149-707f33f5-09be-4dbf-8207-609902def480.png)

**Comment by prabjot09** [comment]
Resolved: User is warned whenever they try to submit input with unicode characters. Items with unicode characters aren't created.
