### ISSUE TITLE
Int32 overflow on units

### ISSUE THREAD

**Issue by shonviv** [Abdi-F/EECS3311-Group-13#3]
Setting the quantity of an item as the Int32 limit (-1) and then increment results in an overflow:
![image](https://user-images.githubusercontent.com/20226454/225698438-d09bd98b-5dfa-4ae8-a317-2e2492e22541.png)

**Comment by prabjot09** [comment]
Resolved: Item stock can be set to a maximum of 256 units and can't be incremented above that amount.
